### ISSUE TITLE
!submit message removal right after issue submission

### ISSUE THREAD

**Issue by actuallylost** [actuallyori/sfe-quality-assurance#4]
When the user successfully executes the command !submit and submit an issue, it should almost instsntly be deleted (the messsge including the command) and if not used correctly the command message should be deleted after around 2-3 seconds

**Comment by kaylendog** [comment]
By "not used correctly", do you mean incorrect syntax? Because, if so, that isn't possible as that's something jisco don't currently support.

**Comment by actuallylost** [comment]
If for example they do !sumit, or !submit<issue> (no spaces)

**Comment by kaylendog** [comment]
Fixed
